version: "3.0"
services:
  my_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - my_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://my_db:5432/my_db'
      JAVA_OPTS: '-Xmx512m'